version: "3"
name: rag-app 

services:
  postgres:
    build:
      context: ./
      dockerfile: pg.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql
      # - ./postgres/0-vector-extension.sh:/docker-entrypoint-initdb.d/0-vector-extension.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

  streamlit-app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    command: streamlit run streamlit_app.py --server.port 8501
    volumes:
        - ./:/usr/src/app
    ports:
        - 8501:8501
    image: rag-streamlit:latest

volumes:
  postgres_data: